### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by ulysses4ever** [hackage-trustees/hackage-cli#14]
Maybe it makes sence to have the tool released on Hackage?

**Comment by sol** [comment]
@andreasabel @phadej can we have this on Hackage please?

**Comment by andreasabel** [comment]
https://hackage.haskell.org/package/hackage-cli says:
```
Package not found

No such package in package index.
```
However, uploading a candidate fails:
```
Error uploading
hackage-cli/dist-newstyle/sdist/hackage-cli-0.1.0.0.tar.gz:
http code 403
Error: Upload failed

You are not authorised to upload candidates of this package. The package
'hackage-cli' exists already and you are not a member of the maintainer group
for this package.

If you believe you should be a member of the maintainer group for this
package, then ask an existing maintainer to add you to the group. If this is a
package name clash, please pick another name or talk to the maintainers of the
existing package.
```
@hvr @phadej Any clue what is going on here?

**Comment by sjakobi** [comment]
It seems that @hvr has reserved the name in some way: https://hackage.haskell.org/package/hackage-cli/maintainers/

**Comment by andreasabel** [comment]
> It seems that @hvr has reserved the name in some way: [hackage.haskell.org/package/hackage-cli/maintainers](https://hackage.haskell.org/package/hackage-cli/maintainers/)

Yeah, this was exactly my suspicion.  Wouldn't be Herbert if he didn't take some precaution... ;-)
I will try to reach him.

**Comment by andreasabel** [comment]
Well, looks like @hvr uploaded a candidate once: https://hackage.haskell.org/package/hackage-cli-0.1.0.0/candidate

Why is this candidate not listed under https://hackage.haskell.org/package/hackage-cli/candidates?

**Comment by phadej** [comment]
Something changed on Hackage, as e.g. https://hackage.haskell.org/user/phadej doesn't show packages which I name squatted myself either. It did previously.

**Comment by andreasabel** [comment]
Released! https://hackage.haskell.org/package/hackage-cli
