### ISSUE TITLE
hackage-cli: src/Main.hs:381:5-99: Irrefutable pattern failed for pattern [vs]

### ISSUE THREAD

**Issue by andreasabel** [hackage-trustees/hackage-cli#22]
```
$ hackage-cli list-versions --help
Usage: hackage-cli list-versions PKGNAME [--no-annotations] [--rev-urls]
  list versions for a package
...
$ hackage-cli list-versions Agda
hackage-cli: src/Main.hs:381:5-99: Irrefutable pattern failed for pattern [vs]
...
$ hackage-cli --version
hackage-cli 0.1.0.0
```

**Comment by sjakobi** [comment]
This is the function where the error arises:

https://github.com/hackage-trustees/hackage-cli/blob/6c7e7986eca6865aa2b7dddd0285549023cb18a5/src/Main.hs#L378-L411

Apparently this function is used to scrape package versions from Hackage pages:

https://github.com/hackage-trustees/hackage-cli/blob/6c7e7986eca6865aa2b7dddd0285549023cb18a5/src/Main.hs#L302-L306

I guess that the HTML layout was changed earlier this year, so the scraping code no longer works.

I think it would be best if `hackage-cli` would use a more robust approach to discover available package versions. That would probably be the Hackage API: https://hackage.haskell.org/api#versions, e.g. https://hackage.haskell.org/package/containers/preferred.json

**Comment by phadej** [comment]
or https://hackage.haskell.org/package/cabal-install-parsers-0.4.3/docs/Cabal-Index.html

**Comment by sjakobi** [comment]
> or https://hackage.haskell.org/package/cabal-install-parsers-0.4.3/docs/Cabal-Index.html

I think it might be a bit tricky to make this approach perform well. `hackage-cli` supports using different Hackage hosts, via the `--hostname` option. I think this means that we can't easily use the fast `cachedHackageMetadata` function.
