### ISSUE TITLE
Add me to the `hackage-trustees` organization and give me full control over the `hackage-cli` repo

### ISSUE THREAD

**Issue by andreasabel** [hackage-trustees/hackage-cli#34]
I am (a) maintainer of `hackage-cli`. I seem to be the only active maintainer atm (the last commit by non-me was in 2019).
I have write-rights, but I am lacking the full rights to this repo, e.g. I cannot invite another maintainer.

Hereby, I ask
- to be added to the `hackage-trustees` organization
- to be given full control over the `hackage-cli` repository (including changing settings, inviting collaborators).

To me, the only visible members of `hackage-trustees` are @bergmark and @hesselink .  So please, one of you make this happen.  Should there be problems, please inform me.

**Comment by bergmark** [comment]
done! wasn't aware i had these kinds of powers.

**Comment by andreasabel** [comment]
Terrific!
