### ISSUE TITLE
Why ~/.netrc?

### ISSUE THREAD

**Issue by mitchellwrosen** [hackage-trustees/hackage-cli#8]
Hi folks, I'm curious why there is a requirement to store hackage credentials in plaintext in a `~/.netrc` file in order to use this tool.

By comparison, `travis-ci` has a command-line tool that can encrypt arbitrary data like environment variables, using some hard-coded public keys owned by `travis-ci.com`, which allows you to store secrets in public `.travis.yml` files.

**Comment by phadej** [comment]
You don't store your [`~/.aws/credentials`](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) publicly either, do you?

**Comment by phadej** [comment]
edit: it would be nice if operations systems provided easy way to interact with their built-in keychains. But I haven't found that easy.

**Comment by phadej** [comment]
@hvr pointed on IRC that there's a convention to use `~/.netrc.gpg` https://bryanwweber.com/writing/personal/2016/01/01/how-to-set-up-an-encrypted-netrc-file-with-gpg-for-github-2fa-access/

I can implement that feature, I have done something similar already for myself before.

**Comment by hvriedel** [comment]
This is being addressed by #12

**Comment by amigalemming** [comment]
`cabal upload` asks for the password if not stored in `.cabal/config`. I'd prefer this behaviour for `hackage-cli`, too. That is, if password is missing in `.netrc` then `haskage-cli` should ask for it on the command line.
